In [1]:
import numpy as np

In [2]:
revenue_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
unit_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit_ver = np.array([[20],[30],[15]])
price_per_unit_hor = np.array([20,30,15])

In [3]:
revenus_rp = revenue_usd*75
revenus_rp

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [11]:
price_per_unit_ver*unit_sold

array([[1000, 1200,  500],
       [ 300,  390,  150],
       [ 600, 1050,  780]])

In [8]:
np.dot(price_per_unit_ver,unit_sold)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [7]:
np.dot(price_per_unit_hor,unit_sold) #order matters in matrix multiplication

array([1900, 2640, 1430])