In [1]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('sonar_dataset.csv',header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
44   0.0257  0.0447  0.0388  0.0239  0.1315  0.1323  0.1608  0.2145  0.0847   
13   0.0090  0.0062  0.0253  0.0489  0.1197  0.1589  0.1392  0.0987  0.0955   
80   0.0229  0.0369  0.0040  0.0375  0.0455  0.1452  0.2211  0.1188  0.0750   
188  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
131  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346   

         9   ...      51      52      53      54      55      56      57  \
44   0.0561  ...  0.0096  0.0153  0.0096  0.0131  0.0198  0.0025  0.0199   
13   0.1895  ...  0.0059  0.0095  0.0194  0.0080  0.0152  0.0158  0.0053   
80   0.1631  ...  0.0064  0.0022  0.0122  0.0151  0.0056  0.0026  0.0029   
188  0.2119  ...  0.0096  0.0103  0.0093  0.0025  0.0044  0.0021  0.0069   
131  0.5378  ...  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190  0.0141   

         58      59  60  
44   0.0255  0.0180   R  
13   0.0189  0.0102   R  
80   0.0104  0.0163   R  
188  0.0060  0.0018   M  
131  0.0068  0.0086   M  

[5 rows x 61 columns]

In [3]:
df.shape

(208, 61)

In [4]:
df.isnull().sum() #check if there is null

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [6]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [7]:
x = df.drop(60,axis='columns')
y = df[60]

In [8]:
y = pd.get_dummies(y, drop_first=True) #if only 2 dummies can drop 1
y.sample(5)

R
126  0
74   1
71   1
201  0
97   0

In [9]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=1)

In [11]:
x_train.shape, x_test.shape

((156, 60), (52, 60))

In [12]:
model = keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 4ms/step - loss: 0.6915 - accuracy: 0.4946
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6707 - accuracy: 0.6087
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6525 - accuracy: 0.6407
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6426 - accuracy: 0.6998
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6133 - accuracy: 0.7293
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5827 - accuracy: 0.7609
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5673 - accuracy: 0.8020
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5336 - accuracy: 0.7587
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5048 - accuracy: 0.7636
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4843 - accuracy: 0.8205
Epoch 11/

20/20 [==============================] - 0s 4ms/step - loss: 0.0128 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0083 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0075 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0104 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0066 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 4ms/step - loss: 0.0070 - accuracy: 1.0000
Epoch 93/100


In [13]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 1.0061 - accuracy: 0.7500


[1.0060828924179077, 0.75]

In [14]:
y_pred = model.predict(x_test).reshape(-1)
y_pred[:10]

array([4.8083391e-09, 9.6238887e-01, 9.9380046e-01, 7.8293915e-06,
       9.9999738e-01, 9.9979192e-01, 2.3229849e-02, 9.9999976e-01,
       4.0060645e-06, 9.9999976e-01], dtype=float32)

In [15]:
y_pred = np.round(y_pred)
y_pred[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [16]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.89      0.79        27
           1       0.83      0.60      0.70        25

    accuracy                           0.75        52
   macro avg       0.77      0.74      0.74        52
weighted avg       0.77      0.75      0.74        52



In [18]:
modeld = keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

modeld.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 5ms/step - loss: 0.7702 - accuracy: 0.4658
Epoch 2/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6993 - accuracy: 0.5249
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7172 - accuracy: 0.4702
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6686 - accuracy: 0.6325
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7136 - accuracy: 0.4457
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7033 - accuracy: 0.5342
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6690 - accuracy: 0.5414
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6859 - accuracy: 0.5416
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7000 - accuracy: 0.5438
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6655 - accuracy: 0.6191
Epoch 11/

20/20 [==============================] - 0s 4ms/step - loss: 0.3084 - accuracy: 0.8863
Epoch 84/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3078 - accuracy: 0.9150
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3330 - accuracy: 0.8711
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3239 - accuracy: 0.8570
Epoch 87/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2776 - accuracy: 0.8798
Epoch 88/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2904 - accuracy: 0.9202
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2798 - accuracy: 0.9178
Epoch 90/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2897 - accuracy: 0.9087
Epoch 91/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2709 - accuracy: 0.8870
Epoch 92/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2708 - accuracy: 0.9189
Epoch 93/100


In [19]:
modeld.evaluate(x_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.4288 - accuracy: 0.8269


[0.42877641320228577, 0.8269230723381042]

In [23]:
y_pred_d = modeld.predict(x_test).reshape(-1)
y_pred_d = np.round(y_pred_d)
y_pred_d[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [21]:
print(classification_report(y_test,y_pred_d))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84        27
           1       0.86      0.76      0.81        25

    accuracy                           0.83        52
   macro avg       0.83      0.82      0.83        52
weighted avg       0.83      0.83      0.83        52

